# Generated by Django 2.1.4 on 2018-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0002_auto_20181212_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='predictdata',
            name='start_date',
            field=models.DateField(),
        ),
    ]
