# Generated by Django 2.1.4 on 2018-12-22 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0004_auto_20181213_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ri_qi', models.CharField(max_length=30)),
                ('zi_jin', models.IntegerField(default=0)),
                ('qiang_du', models.IntegerField(default=0)),
                ('feng_xian', models.IntegerField(default=0)),
                ('zhuan_qiang', models.IntegerField(default=0)),
                ('chang_yu', models.IntegerField(default=0)),
                ('jin_zi', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_predict.Company')),
            ],
        ),
    ]
