# Generated by Django 2.1.4 on 2018-12-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0005_stockindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindex',
            name='zong_he',
            field=models.IntegerField(default=0),
        ),
    ]
